debian: avoid build non-linux arch (debian#823011)
 non-linux arch build was failed with
>> internal.h:8:33: fatal error: linux/firewire-cdev.h: No such file or directory

debian/control says "arch: any" but it seems that it should be linux-any.

This library is an application of Linux FireWire subsystem and Linux sound
subsystem, therefore it's not portable to non-linux kernel such as kfreebsd.

Reported-by: Hideki Yamane <henrich@debian.or.jp>
Reviewerd-by: HAYASHI Kentaro <kenhys@gmail.com>
Link: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823011