Add missing internal.h
This commit fixes following the error:

  fw_unit.c:9:22: fatal error: internal.h: No such file or directory
  compilation terminated.